name: esencia_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  google_fonts: ^6.2.1
  logger: ^2.6.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/SoloLogo.png
    - assets/icons/NombreyLogo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icons/SoloLogo.png"
  min_sdk_android: 21


